/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package The_Game;

/**
 *
 * @author Kiwiocia
 */
public class DnD_character_Maker extends javax.swing.JFrame {

    /**
     * Creates new form DnD_character_Maker
     */
    public DnD_character_Maker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField10 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(209, 167, 71));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(209, 167, 71));
        jTextField8.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 36)); // NOI18N
        jTextField8.setText("D&D 5e Character Builder");
        jTextField8.setCaretColor(new java.awt.Color(226, 187, 61));
        jTextField8.setDisabledTextColor(new java.awt.Color(226, 187, 61));
        jTextField8.setDoubleBuffered(true);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(209, 167, 71));
        jTextField9.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 24)); // NOI18N
        jTextField9.setText("By : Kiwioca (Andrew)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(497, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("The Cover", jPanel4);

        jPanel1.setBackground(new java.awt.Color(239, 219, 148));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(239, 219, 148));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\tThis Program will aid in the creation of a character for Dungeons and Dragons Fifth\neddition. This program does not include any classes or races from the Expantion Packs \"Xanthar's\nGuide to Everything\", \"Sword Coast Adventurer's Guide\", \"Dungeon Master's Guide\", \"Elemental\nEvil Player's Companion\", \"Volo's Guide to Mosnters\", \"Undearth Arcana\" or \"Out Of The Abyss\"\nThis character builder will also explain the basics of how Dungeons and Dragons is played\n\n\t\n\tThe Basics, to Quote from the player handbook:\n\n\tDungeons & Dragons is a roleplaying board game about storytelling in worlds of swords and \nsorcery. It shares elements with childhood games of make-believe. Like those games, D & D is driven by \nimagination. It’s about picturing the towering castle beneath the stormy night sky and imagining how a fantasy\nadventurer might react to the challenges that scene presents. Players roll dice to resolve whether their attacks \nhit or miss or whether their adventurers can scale a cliff, roll away from the strike of a magical lightning bolt,\nor pull off some other dangerous task. \n\n\tIn Dungeons & Dragons, each player creates an adventurer (also called a character) and teams up\n with other adventurers (played by friends).Working together, the group might explore a dark dungeon, a \nruined city, a haunted castle,or maybe a lost temple deep in a jungle.\n\n\tOne player, however, takes on the role of the Dungeon Master (DM), the game’s lead storyteller\nand referee. The DM creates adventures for the characters, who navigate its hazards and decide which paths to \nexplore. The DM might describe the entrance to Castle Ravenloft, and the players decide what they want their \nadventurers to do. The DM determines the results of the adventurers’ actions and narrates what they experience.\n\n");
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(11, 8, 35));
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(239, 219, 148));
        jTextField1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 24)); // NOI18N
        jTextField1.setText("Welcome to Kiwiocia's DnD 5e Character Builder");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Intro", jPanel1);

        jPanel3.setBackground(new java.awt.Color(239, 219, 148));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(239, 219, 148));
        jTextField7.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 18)); // NOI18N
        jTextField7.setText("How the Game is played");

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(239, 219, 148));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("\t\n\tThe Game can be simple put into a three step back and forth communication between player \nand DM. Weither in combat or not, this basic formula is followed:\n\n\t1. The DM describes the enviroment \n\t\t(The land nearby, what enemies are doing, what the individual players can see\n\t\tthe DM also role plays at the characters in the setting)\n\t2. The players decide what they want to\n\t3. The DM narrates the result\n\nHere's a made up example:\nContext (There is a Barbarian, a Rogue, and a Druid walk into a tavern)\n(step 1)                   DM: \"you arrive at a tavern, no one is outside and the lights are on inside, it sounds \n                                        like there are a few people there\"\n(step 2) Barbarian's Player: \"I walk in\"\n                Rogue's player: \"same here\"\n                 Druid's player: \"me too\"\n(step 3)\t         DM: \"As you walk in you are greeted by a male tiefling barkeep\"\n(step 1)   DM as Barkeep: \"Welcome to the Tipsy Tiefling, we've got a few open rooms and plenty to drink. \n\t                  What can I get for you three?\"\n\nThis process reapeats for the whole game, a back and forth interaction between player and DM.\n           ");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Intro 2", jPanel3);

        jPanel2.setBackground(new java.awt.Color(247, 235, 195));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(247, 235, 195));
        jTextField2.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jTextField2.setText("Basic Terms that everyone should know");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(247, 235, 195));
        jTextField3.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jTextField3.setText("D(x)");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(247, 235, 195));
        jTextField4.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jTextField4.setText("When the term D20, or D6 or D8 is used, it refers to a dice with that many faces. Ex (D20 = 20 sided dice, D6 = 6 sided)");

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(247, 235, 195));
        jTextField5.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jTextField5.setText("D100");

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(247, 235, 195));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("\tThe D100 is a little bit different, it consists of 2 die rolls, a D10 and a percentile dice, which is a D10 \nbut it goes up by 10 instead of 10 (sides go from 00 to 10 to 90). These 2 die are rolled at the same time and added to \neach other. (ex D10 = 9, D% = 50, result is 59)");
        jScrollPane3.setViewportView(jTextArea3);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(247, 235, 195));
        jTextField6.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jTextField6.setText("Ability Scores");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(247, 235, 195));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\t\n\tEach character and monster has capablities that are defined by Ability scores, There are 6 ability scores, \nthey are as follows:\n\tStrength: A measure of the beings athleticism or bodily power, this would modify your character's ability \n\t               to do physicly strenuous tasks like a running long jump or carrying a heavy object\n\tDexterity: A measure of Physical Agility, Balance, Reflexes, Overall nimbelness. This would effect \n\t               meticulous or agile tasks such as lockpicking, hiding or pickpocketing\n\tConstitution: A measure of vital force, health, stamina. This would effect a characters sturdiness, or \n\t                   a resistance to a poison.\n\tIntelligence: A measure of Mental acuity, information recall, analytical skill. This would effect your \n\t                  character's ability to remeber past events, lore of town, this also effects a wizzard's ability to\n\t                  cast spells.\n\tWisdom: A measure of Awareness, intuition, insight. This would effect your characters ability to perceive\n\t              distant objects, to stay alert and general knowledge like medicine, nature or survival.\n\tCharisma: A measure of Confidence, eloquence, leadership. This effects your character's ability to\n\t               persuade and convince others to help do your bidding");
        jScrollPane2.setViewportView(jTextArea2);

        jTextField10.setText("Ability Modifiers");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField4)
                                        .addComponent(jScrollPane3)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jScrollPane2))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Terms to know", jPanel2);

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 18)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("\t\n\tMaking a character in dungeons and dragons is a seemingly complicated and lengthy \nprocess that can intimidate new players that are used to the normal RPG character maker, where all the \npresets and what you want are just given quickly without any math being performed. The Whole point of\nthis program to make that lengthly process much quicker.\n\n\tSo here are the Basics of character building:\n\n\tFirst, off You'll need 4 D6, 4 Six-Sided Die, This will be needed to determine your\ncharacter's ability scores. You'll first decide your race (as in like species as a whole), your class, and then\nyour background. The player handbook (PH) recommends this order of making a character.\n    \n\t\t     That is a dumb approach\n\n\tThe better method of doing this is to decide your Class first, this is because the class\nthat you choose is more effective with certain ability scores being higher than others (ex Rogues are \nbetter if they have a higher Dexterity score, Paladins are better with Constitution and Strength, etc). \nThis means that if you know which class you want, then deciding the right race is much easier because\neach race as certain proficiencies and bonuses to ability scores (ex Dwarves get bonuses to constitution, \nso they would make for better paladins than they would, say, a wizard). Then finishing off with\nbackground because background is more useful to your character as a story background. Yes, it is highly\nrecommended that you have a background story for your character. It's quite helpful and easier to roleplay\na character that has a purpose that they search for, it just in general make the game much more fun to\nplay.");
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("How this works", jPanel6);

        jTextField11.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jTextField11.setText("Classes: Broken down and explained");

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 16)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("\n\tBarbarian: A fierce warrior of a primitive background who can enter a battle rage,  Strength and \nConstitution, light and medium armor, shields, simple and martial weapons. They are a basic character Class that uses\nyour basic sword, axe, hammer, etc. As stated, they can enter a state of battle rage, which allows them to hit harder.\n\n\tBard: An inspiring magician whose power echoes the music of creation, Dexterity & Charisma, \nlight armor, simple weapons, hand crossbows, longswords, rapiers, shortswords. Bards are an odd class, they are kinda\ngood at everything, but not amazing at anything.\n\n\tA priestly champion who wields divine magic in service of a higher power, d8, Wisdom & Charisma, \nlight and medium armor, shields, simple weapons. They are a blend of a beefy melee warior");
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab2", jPanel7);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("The Character Maker", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DnD_character_Maker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DnD_character_Maker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DnD_character_Maker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DnD_character_Maker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DnD_character_Maker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
